from .auth import auth_bp
from .dashboard import dashboard_bp
from .sellers import sellers_bp
from .employees import employees_bp
from .work_allocations import wa_bp
from .purchase import pur_bp
from .sales import sale_bp
from .coa import coa_bp
from .lookups import lookups_bp